# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Saferm < Formula
  desc "AI-first safe rm replacement"
  homepage "https://github.com/smm-h/saferm"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smm-h/saferm/releases/download/v0.1.3/saferm_0.1.3_darwin_amd64.tar.gz"
      sha256 "a1d815779bcc5bd0fcc52b832535feace925c75f22358a47cae37c1d215eb75e"

      define_method(:install) do
        bin.install "saferm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smm-h/saferm/releases/download/v0.1.3/saferm_0.1.3_darwin_arm64.tar.gz"
      sha256 "395b63ad4ca9d0d7c546473f2b3a5277cb979bc5a8a2d586f36486c022eebad0"

      define_method(:install) do
        bin.install "saferm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smm-h/saferm/releases/download/v0.1.3/saferm_0.1.3_linux_amd64.tar.gz"
      sha256 "32fee62d4a84218485a003f3e99a728ff2708f111e3702965afaff2cbf9751aa"
      define_method(:install) do
        bin.install "saferm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smm-h/saferm/releases/download/v0.1.3/saferm_0.1.3_linux_arm64.tar.gz"
      sha256 "01e3a609c5df30b04a872a1ed0badfddaab920a297979783d8cc9a36675f52a3"
      define_method(:install) do
        bin.install "saferm"
      end
    end
  end

  test do
    system "#{bin}/saferm", "--version"
  end
end
