# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Saferm < Formula
  desc "AI-first safe rm replacement"
  homepage "https://github.com/smm-h/saferm"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smm-h/saferm/releases/download/v0.1.2/saferm_0.1.2_darwin_amd64.tar.gz"
      sha256 "02ee2ce4e8b2a280b416bad850b9ddbac218bb2bb0f266966ece77972d4e8434"

      define_method(:install) do
        bin.install "saferm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smm-h/saferm/releases/download/v0.1.2/saferm_0.1.2_darwin_arm64.tar.gz"
      sha256 "0f92d4d5531178caefb32e38ab1e7db5814f2ca253e655f0b6450ad39439bc2d"

      define_method(:install) do
        bin.install "saferm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smm-h/saferm/releases/download/v0.1.2/saferm_0.1.2_linux_amd64.tar.gz"
      sha256 "cfacde5e3193c8813f988806317b9d100288b6fe1fcab603acc8ae68e7cb00c4"
      define_method(:install) do
        bin.install "saferm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smm-h/saferm/releases/download/v0.1.2/saferm_0.1.2_linux_arm64.tar.gz"
      sha256 "9778a8eb6bc73f744eb8caddf1da9e06c9af1e7f3df9a14452acd70e860a6c1f"
      define_method(:install) do
        bin.install "saferm"
      end
    end
  end

  test do
    system "#{bin}/saferm", "--version"
  end
end
